name: Update Key Every 2 Minutes

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate random key and write to Key.txt
        run: |
          openssl rand -base64 24 > Key.txt

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Auto-update Key.txt with random key"
          github_token: ${{ secrets.GITHUB_TOKEN }}
