name: Update Key File Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Key.txt
        run: |
          echo "NewKeyHere" > Key.txt  # Replace with your actual key logic or generate one

      - name: Commit and push updated Key.txt
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update Key.txt every 5 minutes"
