name: Update Daily Key

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 00:00 UTC

jobs:
  update-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate new key
      run: |
        NEW_KEY=$(openssl rand -hex 8)
        echo "$NEW_KEY" > key.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add key.txt
        git commit -m "Daily key update"
        git push
